@ECHO OFF
IF DEFINED APPDATA SET APPDATA
IF DEFINED HOMEPATH SET HOMEPATH
IF DEFINED LOCALAPPDATA SET LOCALAPPDATA
IF DEFINED USERDOMAIN SET USERDOMAIN
IF DEFINED USERDOMAIN_ROAMINGPROFILE SET USERDOMAIN_ROAMINGPROFILE
IF DEFINED USERNAME SET USERNAME
IF DEFINED USERPROFILE SET USERPROFILE